version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building PetClinic..."
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Build completed at `date`"
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
